apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vas-mdm-awsmi-pvc-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc
  volumeName: vas-mdm-awsmi-pv-01